export const skillsList = [
    "JavaScript",
    "TypeScript",
    "React",
    "Next.js",
    "Vue.js",
    "Angular",
    "Node.js",
    "Express.js",
    "MongoDB",
    "MySQL",
    "PostgreSQL",
    "HTML",
    "CSS",
    "Tailwind CSS",
    "Redux",
    "GraphQL",
    "REST API",
    "AWS",
    "Docker",
    "Kubernetes",
    "Python",
    "Django",
    "Flask",
    "Java",
    "Spring Boot",
    "C++",
    "Git",
    "Linux"
  ];